- name: Deploy the Tankerkönig Exporter
  hosts: all
  gather_facts: true

  roles:
    - role: suhlig.simple_systemd_service
      vars:
        program:
          # TODO use {{ ansible_architecture }} and {{ ansible_system | downcase }}
          binary: "{{ playbook_dir }}/../dist/{{ program_name }}_linux_amd64/{{ program_name }}"
          name: tankerkoenig-exporter
          description: Tankerkönig data export for Prometheus
          parameters: --interval 15m "{{ tankerkoenig.stations }}"
          environment:
            - "TANKERKOENIG_API_KEY='{{ tankerkoenig.api_key }}'"
      become: true
