- name: Deploy the Tankerkönig InfluxDB Importer
  hosts: all
  gather_facts: true

  roles:
    - role: suhlig.simple_systemd_service
      vars:
        program:
          # TODO use {{ ansible_architecture }} and {{ ansible_system | downcase }}
          binary: "{{ playbook_dir }}/../dist/{{ program_name }}_linux_amd64/{{ program_name }}"
          name: tankerkoenig-influxdb-importer
          description: Tankerkönig data export to InfluxDB
          parameters: "{{ tankerkoenig.stations }}"
          environment:
            - "TANKERKOENIG_API_KEY='{{ tankerkoenig.api_key }}'"
            - "INFLUXDB_URL='{{ influxdb_url }}'"
          timer:
            - OnUnitActiveSec=15m
      become: true
